sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_93d5862f78de_key -iv $encrypted_93d5862f78de_iv -in storage-service-account.json.enc -out storage-service-account.json -d
  - openssl aes-256-cbc -K $encrypted_f61f33b076e9_key -iv $encrypted_f61f33b076e9_iv -in compute-service-account.json.enc -out scripts/deploy-dev/compute-service-account.json -d
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - bash ./scripts/build-image.sh

script:
  - echo "SUCCESS- TEST"

deploy:
  provider: script
  script: bash scripts/deploy-dev/start-deploy.sh
  on:
    branch: dev
