sudo: required

language: ruby

services:
  - docker

before_install:
  - bash ./scripts/build-image.sh

deploy:
  provider: script
  script: docker build -t deploy-dev ./scripts/deploy-dev && docker run deploy-dev
  on:
    branch: deploy-test
