FROM node:18.12.1-alpine

RUN apk update
RUN apk add dos2unix && apk add bash

WORKDIR /home/app
COPY yarn.lock .
COPY package.json .
RUN yarn install
RUN export NODE_OPTIONS=--max-old-space-size=3000

COPY . .
RUN dos2unix scripts/*.sh

CMD [ "npm", "run", "docker-start" ]