version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=storage-service-account.json
      - JWT_SECRET=Yasuoganktem20gg
      # - STORAGE_FOLDER=toan-dev-003
      - STORAGE_FOLDER=storage-folder
      - DB_HOST=postgres-db
      - DB_USER_NAME=postgres
      - DB_PASSWORD=Toan1234
      - DB_NAME=schoolX-dev
      - EMAIL_SENDER=schoolx.dev.001@gmail.com
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_HOST=${MAILGUN_HOST}

      - JS_MINI_SERVER=http://js-server:6001
      - JAVA_MINI_SERVER=http://java-server:6002
      - PYTHON_MINI_SERVER=http://python-server:6003
      - CPP_MINI_SERVER=http://cpp-server:6004
    volumes:
      - ./src:/home/app/src
      - /home/app/node_modules
      - /home/app/src/migrations
    depends_on:
      - postgres-db
    command:
      [
        'bash',
        './scripts/wait-for-it.sh',
        '--timeout=180',
        'postgres-db:5432',
        '--',
        'npm',
        'run',
        'start:docker',
      ]

  # js-server:
  #   build:
  #     context: ./servers/js
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 6001:6001
  #   volumes:
  #     - /home/app/node_modules
  #     - ./servers/js:/home/app

  # java-server:
  #   build:
  #     context: ./servers/java
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 6002:6002
  #   volumes:
  #     - /home/app/node_modules
  #     - ./servers/java:/home/app

  python-server:
    build:
      context: ./servers/python
      dockerfile: Dockerfile.dev
    ports:
      - 6003:6003
    volumes:
      - /home/app/node_modules
      - ./servers/python:/home/app

  cpp-server:
    build:
      context: ./servers/cpp
      dockerfile: Dockerfile.dev
    ports:
      - 6004:6004
    volumes:
      - /home/app/node_modules
      - ./servers/cpp:/home/app

  postgres-db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Toan1234
      - POSTGRES_DB=schoolX-dev
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 4001:8080
