version: '2'
services:
  app:
    image: superknife0512/schoolx-graphql
    ports:
      - 3001:3001
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=storage-service-account.json
      - JWT_SECRET=Yasuoganktem20gg
      # - STORAGE_FOLDER=toan-dev-003
      - STORAGE_FOLDER=storage-folder
      - DB_HOST=postgres-db
      - DB_USER_NAME=postgres
      - DB_PASSWORD=Toan1234
      - DB_NAME=schoolX-dev
      - EMAIL_SENDER=schoolx.dev.001@gmail.com
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}

      - JS_MINI_SERVER=http://js-server:6001
      - JAVA_MINI_SERVER=http://java-server:6002
      - PYTHON_MINI_SERVER=http://python-server:6003
    depends_on:
      - postgres-db
    command:
      [
        'bash',
        './scripts/wait-for-it.sh',
        '--timeout=180',
        'postgres-db:5432',
        '--',
        'npm',
        'run',
        'start-prod:docker',
      ]

  js-server:
    image: superknife0512/schoolx-js-server

  java-server:
    image: superknife0512/schoolx-java-server

  python-server:
    image: superknife0512/schoolx-python-server

  postgres-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Toan1234
      - POSTGRES_DB=schoolX-dev
    volumes:
      - /home/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 4001:8080
