FROM node:18.12.1

RUN apt-get update -y
RUN apt-get install -y dos2unix

WORKDIR /home/app
COPY package.json .
COPY yarn.lock .
RUN yarn install
RUN export NODE_OPTIONS=--max-old-space-size=3000

COPY . .
RUN dos2unix scripts/*.sh

CMD [ "npm", "run", "docker-start" ]