
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim-dev
  namespace: dev
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migrate-claim-dev
  namespace: dev
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi