version: 2.1

jobs:
  build_dev:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - run:
          name: build docker
          command: bash ./scripts/build-image.sh
  deploy_dev:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - run:
          name: deploy
          command: docker build -t deploy-dev ./scripts/deploy-dev && docker run deploy-dev

workflows:
  build_and_deploy_dev:
    jobs:
      - build_dev:
          filters:
            branches:
              only: deploy-test

      - deploy_dev:
          filters:
            branches:
              only: deploy-test
          requires:
            - build
