---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: staging
spec:
  selector:
    component: db-pod
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: staging
  labels:
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: db-pod
  template:
    metadata:
      labels:
        component: db-pod
    spec:
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-claim-staging
      containers:
      - name: db-server
        image: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-storage
        env:  
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata/
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:  
              name: be-credentials
              key: DB_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:  
              name: app-config
              key: DB_USER_NAME
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:  
              name: app-config
              key: DB_NAME
        ports:
        - containerPort: 5432
      restartPolicy: Always