version: '3.9'
services:
  mini-server:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 6004:6004
    volumes:
      - /home/app/node_modules
      - .:/home/app
      - /home/app/cppFiles