FROM node:14 AS nodejs

RUN echo "Install nodejs"

FROM openjdk:7 

COPY --from=nodejs . .

WORKDIR /home/app

COPY package.json .

RUN npm i

COPY . .

RUN apt-get update -y
RUN apt-get install -y dos2unix
RUN chmod 700 ./runJavaCode.sh
RUN dos2unix ./runJavaCode.sh

CMD ["npm", "run", "start"]