version: "3.9"
services: 
  app: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /home/app/node_modules
      - .:/home/app
    ports: 
      - 6003:6003