name: Unit testing
on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read # Required when overriding permissions
  pull-requests: write # <== Add this to allow action to modify your PR

jobs:
  unit-test:
    if: ${{ contains(github.event.review.body, 'ok to test') && contains(github.event.review.state, 'approved') }} # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install dependencies
        run: yarn install

      - name: Coverage code
        run: yarn run test:cov

      - name: Test Result Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Unit test report # Name of the check run which will be created
          path: ./report.xml # Path to test results
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
        # filter-changed-files: true
